[build]
  base = "exampleSite"
  command = "go env -w GOPROXY=https://proxy.golang.org,direct && hugo mod get -u ./... && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.0"
  GO_VERSION = "1.22.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.0"
  GO_VERSION = "1.22.0"
