[build]
  base = "exampleSite"
  command = "hugo --gc --minify -b $URL"
  publish = "public"


[build.environment]
  HUGO_VERSION = "0.125.0"
  GO_VERSION = "1.22.0"


  # HUGO_VERSION   = "0.147.0"
  # HUGO_ENV       = "production"
  # HUGO_THEMESDIR = "../.."
  # HUGO_THEME     = "repo"
  # TZ             = "Europe/Paris"


[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.0"
  GO_VERSION = "1.22.0"
  
# [context.production.environment]
# HUGO_VERSION = "0.100.2"

[context.deploy-preview]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.deploy-preview.GO_VERSION = "1.22.0"    # Requis pour télécharger les Hugo Modulesenvironment]
HUGO_VERSION = "0.100.2"

[context.branch-deploy]
command = "cd exampleSite && hugo --gc --minify -D -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.100.2"





