[build]
  base = "exampleSite"
  # On crée manuellement le dossier attendu et on y copie les fichiers du thème locaux
  command = "mkdir -p themes/congo && cp -r ../assets ../config ../i18n ../layouts ../static ../theme.toml themes/congo/ && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.0"
