# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
defaultContentLanguage = "fr"
defaultContentLanguage = "fr"

enableRobotsTXT = true
paginate = 15
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    # Mettez les paramètres personnalisés sous le bloc params
    [languages.fr.params]
      title = "Mon super site Congo"
      description = "Description de mon site"
